//
//  Tools.swift
//  collage
//
//  Created by Malia Kuo on 3/26/24.
//

import Foundation
import SwiftUI

//class Tools {
//    var icon: Image
//    var name: String
//    var isActive: Bool
//}
//
//class Selector: Tools {
//    // need to check in on what type the unique id generated by element, model is??
//    var item: String
//    // multiselect later
//}
//
//class Resizer: Selector {
//    var factor: Float
//    
//    func Resize(item: String, factor: Float) -> Void {
//        // resize function
//    }
//}

// apparently copy and paste functions exist in the SwiftUI Clipboard - probably just make each element copyable and pastable
// does this mean creating a new instance of element each time?? confusing
